### ISSUE TITLE
CheckPoint-1 is ready for review

### ISSUE THREAD

**Issue by shanda-matc** [shanda-matc/Expenses#1]
@pawaitemadisoncollege - checkpoint 1 is ready for review

**Comment by pawaitemadisoncollege** [comment]
Hi @shanda-matc! This is such a fun project idea - as an avid reader, I'm really looking forward to progress on this!! 

**Problem Statement** This is such a creative project idea and should easily provide opportunity for you to demonstrate your learning from not only Ent Java, but our entire program. The reference for categories is helpful for the reader to understand what "categories" means in this context.

Ideas for improvement:
- [x] What is your motivation for building this? What problem does it solve?

**User Stories** You've done a good job detailing out specific functionality as individual user stories and identifying the MVP. Your MVP appears to cover the Ent Java requirements of create and read, authentication, and multiple one-to-many relationships. 

Ideas for improvement:
- [ ] I do not see a story for update or delete. Is there a meaningful user story you could add for those? Perhaps edit a story and delete a story?
- [x] I am assuming a "*" indicates MVP? If so, it might be a good idea to explain that so it is clear to everyone.
- [ ] If reporting an inappropriate story is not MVP, should reviewing the inappropriate story also NOT be marked MVP?
- [ ] While the notification feature is a really cool idea, I am not sure if it has to be MVP (at least in terms of ent java requirements) and would make an excellent stretch goal!

One note related to the stories - sign up, sign in, and password reset will be handled by amazon cognito which we learn in week 7, so hold off on building those stories out for now. 

**Screens** You've done a good job showing the home page, sign in, sign up, and writing.

- [ ] I did not see screens for the user story involving leaving comments on a story, or for reading a story (I'm guessing the home page is used for browsing, but not reading the actual story, is that right?)

**Reflection/time log** the weeklyreflection.md provides the right level of detail for what you completed and how long it took. 

**Project plan**

- [x] I could not find this, can you point me to it? 

**Two more things**

- [ ] some files are empty on GitHub (0 bytes) such as application flow.md, tasks.md, ProjectPlan.md, journal.md. I am not sure if they are empty because you haven't added anything yet, or if they are no longer needed. Any that you aren't using should be removed.
- [x] It looks like the link in the student repository's individual project's list for your project is broken. Can you fix it?
