### ISSUE TITLE
Checkpoint 2

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [shanda-matc/Expenses#5]
Hi @shanda-matc! This is a reminder to let me know when Checkpoint 2 is ready for review by replying to this issue:

1. Database designed and created, 
2. at least one DAO with full CRUD (create, read, update, delete) implemented with Hibernate, 
3. DAO is fully unit tested, 
4. Log4J is implemented (no System.out.printlns)
5. Project plan updated with completed tasks
6. Project plan updated with tasks to achieve all user stories

**Comment by shanda-matc** [comment]
@pawaitemadisoncollege. Checkpoint-2 is ready for review

**Comment by pawaitemadisoncollege** [comment]
Hi @shanda-matc! Following are things I noticed while reviewing for checkpoint 2:

**Database designed and created** I compared the user stories to the database design, and noticed the following:

- [x] I noticed a few typos: Stories table is Strories, comment_id is commnet_id. There are a few others too. Best to clean these up so it looks professional. 
- [x] Since cognito is handling authentication, there's no need to store the password on the Users table.
- [x] User stories don't appear to be marked mvp? Are you planning to build all of them? I recommend slimming this down to cover stories with full crud. Given the short timeframe until the end of this semester, I wonder if it makes sense to exclude the report portion, too. 
- [x] User stories would improved by indicating which ones are for a logged-in user versus not. 
- [x] The db shows authors and users. Does this mean one user could have many author names/bios - I don't see a user story for this. It might be simpler for version 1 to use eliminate the author table and use only the user able.
- [x] If you do slim down the database for V1, I recommend somehow marking the tables for v1 versus v2.
- [x] Will a user need to be logged in to make a comment on a story? If not, the design is a-ok, if so, there should be a userid on the comment table. 
- [ ] I asked some questions in checkpoint one that I still don't know the answer to. For example - screens for leaving comments on a story or reading a story. 


**At least one DAO with full CRUD (create, read, update, delete) implemented with Hibernate  and  DAO is fully unit tested** Looks good so far. Next steps are to implement the generic dao and add more entities and tests. 


**Log4J is implemented (no System.out.printlns)**  Looks good so far! 


**Project plan updated with completed tasks and Project plan updated with tasks to achieve all user stories**

- [ ] Project plan is missing detail for each user story. 
- [ ] Project plan does not extend past week 9. 

**Time log/journal**

- [ ] This doesn't appear to have been updated recently.
- [ ] There are also a number of empty files, such as timeLog, tasks and journal. Remove those files if you are not using them.
